#!/usr/bin/env bash

set -eo pipefail

# Inspired by https://gist.github.com/akorn/644855ddaa8065f564be

# Define colours for stdout/stderr
RED='\033[0;31m'
GREEN='\033[0;32m'
NC='\033[0m' 		# No Color

# help function showing usage
usage() {
	cat <<- DESCRIPTION >&2
	USAGE
	    $(basename $0) [--parallel=N] [rsync args...]

	OPTIONS
	    --parallel=N    Use N parallel processes for transfer. Default is to use all available processors (nproc) or fal back to 10.

	NOTES
	    * Requires GNU Parallel.
	    * Use with ssh-keys. Lots of password prompts will get very annoying.
	    * Does an itemize-changes first, then chunks the resulting file list and launches N parallel rsyncs to transfer a chunk each.
	    * Be a little careful with the options you pass through to rsync. Normal ones will work, you might want to test weird options upfront.
	DESCRIPTION
}

check_dependencies() {
	if ! command -v parallel &> /dev/null; then
		echo -e "${RED}parallel could not be found${NC}" >&2
		exit 1
	fi
}

parse_arguments() {
	if [[ "$1" == --parallel=* ]]; then
		PARALLEL_RSYNC="${1##*=}"
		shift
	else
		if [[ $(uname) == "Darwin" ]]; then
			PARALLEL_RSYNC=$(sysctl -n hw.ncpu 2> /dev/null || echo 10)
		else
			PARALLEL_RSYNC=$(nproc 2> /dev/null || echo 10)
		fi
	fi
	echo -e "${GREEN}INFO: Using up to ${PARALLEL_RSYNC} processes for transfer ...${NC}" >&2
	RSYNC_ARGS="$*"
}

create_temp_dir() {
	TMPDIR=$(mktemp -d)
	trap 'rm -rf "${TMPDIR}"' EXIT
}

determine_file_list() {
	echo -e "${GREEN}INFO: Determining file list for transfer ...${NC}" >&2
	# sorted by size (descending)
	rsync ${RSYNC_ARGS} --out-format="%l %n" --no-v --dry-run 2> /dev/null \
		| grep -v "sending incremental file list" \
		| sort --numeric-sort --reverse \
		> "${TMPDIR}/files.all"

	# check for nothing-to-do
	TOTAL_FILES=$(wc -l < "${TMPDIR}/files.all")
	TOTAL_SIZE=$(awk '{ts+=$1}END{printf "%.0f", ts}' < "${TMPDIR}/files.all")
	echo -e "${GREEN}INFO: ${TOTAL_FILES} ($(( TOTAL_SIZE/1024**2 )) MB) files to transfer.${NC}" >&2
	if [ "${TOTAL_FILES}" -eq "0" ]; then
		exit 0
	fi
}

array_min() {
	local arr=("$@")
	local min_i=0
	local min_v=${arr[min_i]}
	for i in "${!arr[@]}"; do
		local v=${arr[i]}
		if (( v < min_v )); then
			min_v=$v
			min_i=$i
		fi
	done
	echo "$min_i"
}

initialize_chunks() {
	CHUNKS=()
	for ((I = 0 ; I < PARALLEL_RSYNC ; I++ )); do
		CHUNKS[I]=0
	done
}

balance_by_size() {
	local PROGRESS=0
	local SECONDS=0
	echo -e "${GREEN}INFO: Distributing files among chunks ...${NC}" >&2
	while IFS=' ' read -r FSIZE FPATH || [ -n "$FSIZE" ]; do
		FSIZE=$(echo "$FSIZE" | tr -d '\r')
		FPATH=$(echo "$FPATH" | tr -d '\r')

		if [ -z "$FSIZE" ] || [ -z "$FPATH" ]; then
			echo -e "${RED}WARNING: Invalid line encountered, skipping...${NC}" >&2
			continue
		fi
		PROGRESS=$((PROGRESS+1))

		MIN_I=$(array_min "${CHUNKS[@]}")

		CHUNKS[MIN_I]=$((CHUNKS[MIN_I] + FSIZE))
		echo "${FPATH}" >> "${TMPDIR}/chunk.${MIN_I}"

		if ! ((PROGRESS % 25000)); then
			echo -e "${GREEN}INFO: ${PROGRESS} of ${TOTAL_FILES} (${SECONDS}s)${NC}" >&2
		fi
	done < "${TMPDIR}/files.all"
	echo -e "${GREEN}DONE (${SECONDS}s)${NC}" >&2
}

reverse_alternate_chunks() {
	for ((I = 1 ; I < PARALLEL_RSYNC ; I+=2 )); do
		# If the list of files to transfer is small, we may not have any files to work with
		if [ ! -f "${TMPDIR}/chunk.${I}" ]; then
			continue
		fi

		tac "${TMPDIR}/chunk.${I}" > "${TMPDIR}/chunk.${I}.r" && mv "${TMPDIR}/chunk.${I}.r" "${TMPDIR}/chunk.${I}"
	done
}

start_transfers() {
	echo -e "${GREEN}INFO: Starting transfers ...${NC}" >&2

	# Check if parallel supports the -t option
	if parallel -h 2>&1 | grep -q -- '-t'; then
		PARALLEL_OPTS="-t"
	else
		PARALLEL_OPTS=""
	fi

	find "${TMPDIR}" -type f -name "chunk.*" | parallel -j "${PARALLEL_RSYNC}" ${PARALLEL_OPTS} rsync --files-from={} ${RSYNC_ARGS}
	echo -e "${GREEN}DONE (${SECONDS}s)${NC}" >&2
}

main() {
	if [[ $# -eq 0 ]] || [[ "$1" = "-h" ]] || [[ "$1" = "--help" ]]; then
		usage
		exit 0
	fi

	check_dependencies
	parse_arguments "$@"
	create_temp_dir
	determine_file_list
	initialize_chunks
	balance_by_size
	reverse_alternate_chunks
	start_transfers
}

main "$@"
